sudo: required

# whitelist
branches:
  only:
   - gh-pages   

language: node_js
node_js:
  - "4.1"

before_script:
  - npm install -g json

script: json -f projects.json

notifications:
  hipchat:
    rooms:
      secure: rHHQIGtMcpeuV8gOWdKAu1OFJRLv6rgoiFCEc2ZPdMl96bZ2X1A1E5JnfTdYjUfsr+msSYMTMxHZ5kCwkF24d++VvsUZQMNcb7d7eDM47gaNbrXMwVKuAnONcl6vMzs/5o6YMb3jvxC/fIKTw1jL5H2DjpwR9bqjfLotj+MnNmvmhGs5LkVlu1bZX59zmFjawyRqTPzgogyhHTEf7C+LIcPnfWnr5h8x4oNGa/xF7Q1g4d0pS2K11XXrOYIgvx2ul9YCMnuCWPdXGf6+PBXzpiG2Xa1O46i2UAG5x9Bcckca1bsa1RwnjKgtfD4uk+tVgrPQgHrl0gSElfzkiMG5++nwYlaB1O+1okGdECoH2ZROkinlEcpMCgLu0v+7488kbS/cu85JMCF4Q/53HzBsfbbgWOfOjOUmzt0oSzQtFpeVmCsQhgD/7Bzuu9sh6gBClqOfYevhsZVTUyc/ezaskwoLwpiBMD0OcExl5MdkwVz2IKtJWgibHHoi0RU68B1UHDQhEs7aqWP9TRajFwQG0koSHDhvF6ceBPiyTQ7JK8klcj9RVMOfqW7bbT9P60RkyHdZoxFcTvAlU529RMa+e04FFIvYyt2XdTsYO2QGRzmtXf5TdsWITbKF+Sy8VWCKbwSFaDU7On7numWDwieZI/l650+lVdpiqmu2fdvOiZc=

