sudo: required

# whitelist
branches:
  only:
   - gh-pages   

language: node_js
node_js:
  - "4.1"

before_script:
  - npm install -g json

script: json -f projects.json

notifications:
  hipchat:
    rooms:
      secure: rtu3GvowAOXWJPHapFGN1fpp7QF4poiwuKZX6qXa2XWn2MwekUvt5uPfPbAeoqVXKSy5tjwr9AUN2DQ/r2cm5Ced/a92Ov7DhOUSNFDHVwMd5YGmwvi7zgTimxleev4hTjxV5tqE4meCIcvgh4uCINvV+daITn9C5HY1CX2s2hpKRVvEE6q57qRXm+DXCiCoPV8E1TQg+/UohSTVa2QRs12o2cnb95JXDkNAP3Dx3G3x/4HfcBfBX0EEkYbcNUBtw/1rQoRPePYRTya/SwUExIFl1N4cpInReHUcXAkXSz57CCFjvV8/nYcnLXfrGidSMCCrKGlc8YhY/22m8l1GxWJ75I+Wuh6yotGZtlrvyagQw5SYICJE26XtN1f3vc+wgi3Akvp+eHMEc4+go3dDvU/3FwlLNptuyh66UJX3xTG6q36YUUsXpW18hQhbiQg+2ngiuwcEBBMpmcS1J/hoGdUZfZciHlEYZClcjwp/RRTti1/YIk1RZ17W+cyVOvWCAdMz8iyfJTsQkKZz/wFwTR8JOaKfP6NenhMEBWBnxm2TV4PZXHbtDyHRVijB6so1dMZ768vTFEgnvMVN4i7SWAEIYvqAkUredVPHU05mm2+OVzB6X9waRtwbeT2WC9zCDRZNveaIfBt3QJd6lqiVr9d2i9INpJuXBPCW9rtbUpk=

